<?php namespace ProcessWire;
/**
 * ItrechtConnector
 *
 *
 * By .pupit GmbH (https://www.pupit.de)
 */

class ItrkService extends Process
{

    public static function getModuleInfo()
    {
        return array(
            'title' => 'ITRK-Service',
            'version' => '0.0.1.1',
            'summary' => '',
            'autoload' => true,
            'requires' => array('ProcessWire>=3.0.145', 'PHP>=7.3'),
        );
    }
}